---

- name: Ensure SSH key exists
  user: >
    name={{ ansible_user_id }}
    generate_ssh_key=yes
    ssh_key_file=.ssh/id_rsa

- name: Ensure key exists at DigitalOcean
  digital_ocean: >
    state=present
    command=ssh
    name=my_ssh_key
    ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
  register: my_ssh_key
